package bootstrap

import (
	"github.com/goravel/cos"
	"github.com/goravel/fiber"
	"github.com/goravel/framework/auth"
	"github.com/goravel/framework/cache"
	"github.com/goravel/framework/contracts/foundation"
	"github.com/goravel/framework/crypt"
	"github.com/goravel/framework/database"
	"github.com/goravel/framework/event"
	"github.com/goravel/framework/filesystem"
	"github.com/goravel/framework/grpc"
	"github.com/goravel/framework/hash"
	"github.com/goravel/framework/http"
	"github.com/goravel/framework/log"
	"github.com/goravel/framework/mail"
	"github.com/goravel/framework/process"
	"github.com/goravel/framework/queue"
	"github.com/goravel/framework/route"
	"github.com/goravel/framework/schedule"
	"github.com/goravel/framework/session"
	"github.com/goravel/framework/telemetry"
	"github.com/goravel/framework/testing"
	"github.com/goravel/framework/translation"
	"github.com/goravel/framework/validation"
	"github.com/goravel/framework/view"
	"github.com/goravel/gin"
	"github.com/goravel/minio"
	"github.com/goravel/mysql"
	"github.com/goravel/oss"
	"github.com/goravel/postgres"
	"github.com/goravel/redis"
	"github.com/goravel/s3"
	"github.com/goravel/sqlite"
	"github.com/goravel/sqlserver"
)

func Providers() []foundation.ServiceProvider {
	return []foundation.ServiceProvider{
		&log.ServiceProvider{},
		&cache.ServiceProvider{},
		&session.ServiceProvider{},
		&validation.ServiceProvider{},
		&http.ServiceProvider{},
		&view.ServiceProvider{},
		&route.ServiceProvider{},
		&database.ServiceProvider{},
		&auth.ServiceProvider{},
		&crypt.ServiceProvider{},
		&queue.ServiceProvider{},
		&event.ServiceProvider{},
		&grpc.ServiceProvider{},
		&hash.ServiceProvider{},
		&translation.ServiceProvider{},
		&mail.ServiceProvider{},
		&process.ServiceProvider{},
		&schedule.ServiceProvider{},
		&filesystem.ServiceProvider{},
		&testing.ServiceProvider{},
		&postgres.ServiceProvider{},
		&mysql.ServiceProvider{},
		&sqlserver.ServiceProvider{},
		&sqlite.ServiceProvider{},
		&s3.ServiceProvider{},
		&cos.ServiceProvider{},
		&oss.ServiceProvider{},
		&minio.ServiceProvider{},
		&redis.ServiceProvider{},
		&gin.ServiceProvider{},
		&fiber.ServiceProvider{},
		&telemetry.ServiceProvider{},
	}
}
