package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"goravel/graph/generated"
	"goravel/graph/model"
)

// FindFooByID is the resolver for the findFooByID field.
func (r *entityResolver) FindFooByID(ctx context.Context, id string) (*model.Foo, error) {
	panic(fmt.Errorf("not implemented: FindFooByID - findFooByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
