package feature

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/goravel/framework/support/file"
	"github.com/goravel/framework/support/path"
	"github.com/stretchr/testify/suite"

	"goravel/app/facades"
	"goravel/tests"
)

type InertiaInstallTestSuite struct {
	suite.Suite
	tests.TestCase
	originalWD       string
	appRoot          string
	webRoutesPath    string
	welcomePath      string
	inertiaConfig    string
	rootTemplate     string
	packageJSONPath  string
	viteConfigPath   string
	tsconfigPath     string
	webRoutes        []byte
	welcomeTemplate  []byte
	configSnapshot   []byte
	templateSnapshot []byte
	packageJSON      []byte
	viteConfig       []byte
	tsconfig         []byte
}

func TestInertiaInstallTestSuite(t *testing.T) {
	suite.Run(t, &InertiaInstallTestSuite{})
}

func (s *InertiaInstallTestSuite) SetupSuite() {}

// SetupTest chdirs to the app root (the installer scaffolds relative to CWD),
// snapshots every file the installer overwrites or removes, then runs
// `inertia:install --force`.
func (s *InertiaInstallTestSuite) SetupTest() {
	wd, err := os.Getwd()
	s.Require().NoError(err)
	s.originalWD = wd

	// Resolve every absolute path while CWD is still the test package dir. The
	// framework's path.* helpers build on support.RelativePath ("../.."), which
	// filepath.Abs re-resolves against the current CWD — so they break once we
	// chdir to the app root below.
	s.appRoot = path.Base()
	s.webRoutesPath = path.Route("web.go")
	s.welcomePath = path.View("welcome.tmpl")
	s.inertiaConfig = path.Config("inertia.go")
	s.rootTemplate = path.Resource("inertia", "app.gohtml")
	s.packageJSONPath = filepath.Join(s.appRoot, "package.json")
	s.viteConfigPath = filepath.Join(s.appRoot, "vite.config.ts")
	s.tsconfigPath = filepath.Join(s.appRoot, "tsconfig.json")

	s.webRoutes, err = os.ReadFile(s.webRoutesPath)
	s.Require().NoError(err)
	s.welcomeTemplate, err = os.ReadFile(s.welcomePath)
	s.Require().NoError(err)
	s.configSnapshot, err = os.ReadFile(s.inertiaConfig)
	s.Require().NoError(err)
	s.templateSnapshot, err = os.ReadFile(s.rootTemplate)
	s.Require().NoError(err)
	// The root toolchain is committed, so snapshot it and restore (not delete)
	// it in TearDownTest. The favicon is committed as public/favicon.ico, which
	// the installer leaves untouched; it also generates public/favicon.png, which
	// TearDownTest removes.
	s.packageJSON, err = os.ReadFile(s.packageJSONPath)
	s.Require().NoError(err)
	s.viteConfig, err = os.ReadFile(s.viteConfigPath)
	s.Require().NoError(err)
	s.tsconfig, err = os.ReadFile(s.tsconfigPath)
	s.Require().NoError(err)

	s.Require().NoError(os.Chdir(s.appRoot))

	s.Require().NoError(facades.Artisan().Call("inertia:install --force"))
}

func (s *InertiaInstallTestSuite) TestInertiaInstallGeneratesFiles() {
	// config/inertia.go regenerated by --force (the committed demo imports
	// goravel/app/facades, the install stub imports framework facades).
	s.True(file.Exists(s.inertiaConfig))
	s.True(file.Contains(s.inertiaConfig, "github.com/goravel/framework/facades"))

	// Root template regenerated with the installer's vite stub marker
	// (`resources/js/app.ts`), which the committed template does NOT use (it
	// points at `resources/inertia/app.ts`) — proving --force overwrote the file.
	s.True(file.Contains(s.rootTemplate, `{{ vite "resources/js/app.ts" }}`))

	// Generated demo controllers.
	homeController := filepath.Join(s.appRoot, "app/http/controllers/home_controller.go")
	s.True(file.Contains(homeController, "inertiafacades.Inertia().Render"))
	s.True(file.Contains(homeController, "Defer"))
	s.True(file.Contains(filepath.Join(s.appRoot, "app/http/controllers/feed_controller.go"), "Merge"))
	s.True(file.Contains(filepath.Join(s.appRoot, "app/http/controllers/contact_controller.go"), "FlashErrors"))
	s.True(file.Contains(filepath.Join(s.appRoot, "app/http/controllers/contact_controller.go"), "Redirect"))
	s.True(file.Contains(filepath.Join(s.appRoot, "app/http/controllers/about_controller.go"), "Render"))

	// Generated middleware.
	handleInertia := filepath.Join(s.appRoot, "app/http/middleware/handle_inertia_requests.go")
	s.True(file.Contains(handleInertia, "inertiamw.Handle"))
	s.True(file.Contains(handleInertia, "Share: share"))

	// Frontend scaffolding.
	s.True(file.Exists(filepath.Join(s.appRoot, "package.json")))
	s.True(file.Exists(filepath.Join(s.appRoot, "vite.config.ts")))
	s.True(file.Exists(filepath.Join(s.appRoot, "tsconfig.json")))
	s.True(file.Exists(filepath.Join(s.appRoot, "resources/js/app.ts")))

	// routes/web.go replaced with the installer stub.
	s.True(file.Contains(s.webRoutesPath, "controllers.NewHomeController"))
	s.True(file.Contains(s.webRoutesPath, "appmiddleware.HandleInertiaRequests"))

	// Default Goravel welcome view removed.
	s.False(file.Exists(s.welcomePath))
}

// TearDownTest deletes every file/dir scaffolded by inertia:install, restores
// the snapshotted files, and chdirs back. app/facades/inertia.go is never
// touched: it is generated by package:install, not by inertia:install.
func (s *InertiaInstallTestSuite) TearDownTest() {
	for _, p := range []string{
		s.inertiaConfig,
		s.rootTemplate,
		filepath.Join(s.appRoot, "app/http/controllers/home_controller.go"),
		filepath.Join(s.appRoot, "app/http/controllers/feed_controller.go"),
		filepath.Join(s.appRoot, "app/http/controllers/contact_controller.go"),
		filepath.Join(s.appRoot, "app/http/controllers/about_controller.go"),
		filepath.Join(s.appRoot, "app/http/middleware/handle_inertia_requests.go"),
		filepath.Join(s.appRoot, "resources/js"),
		filepath.Join(s.appRoot, "routes/web.go.bak"),
		filepath.Join(s.appRoot, "routes/web.inertia.go.txt"),
		filepath.Join(s.appRoot, "public/favicon.png"),
	} {
		s.NoError(file.Remove(p))
	}

	// Restore the snapshotted files. A failed restore must abort loudly — a
	// silently-dirty tree would break the next `go build` / `go test`.
	s.Require().NoError(os.WriteFile(s.webRoutesPath, s.webRoutes, 0o644))
	s.Require().NoError(os.WriteFile(s.welcomePath, s.welcomeTemplate, 0o644))
	s.Require().NoError(os.WriteFile(s.inertiaConfig, s.configSnapshot, 0o644))
	s.Require().NoError(os.WriteFile(s.rootTemplate, s.templateSnapshot, 0o644))
	// The root toolchain is committed (the installer overwrites it); restore the
	// committed version rather than deleting it. public/favicon.png is generated
	// by the installer and was removed above.
	s.Require().NoError(os.WriteFile(s.packageJSONPath, s.packageJSON, 0o644))
	s.Require().NoError(os.WriteFile(s.viteConfigPath, s.viteConfig, 0o644))
	s.Require().NoError(os.WriteFile(s.tsconfigPath, s.tsconfig, 0o644))

	// Verify the committed state actually came back, not the install stub.
	s.True(file.Contains(s.webRoutesPath, "appmiddleware.Inertia"))
	s.True(file.Contains(s.inertiaConfig, "goravel/app/facades"))

	s.Require().NoError(os.Chdir(s.originalWD))
}
