name: Test AI
on:
  pull_request:
env:
  # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  # GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
jobs:
  test:
    strategy:
      matrix:
        go: [ "stable" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Go mod cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 10m -v ./tests/feature -run "^TestAITestSuite$"
